apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      env: dev
      project: My-Happy-Web
      role: frontend
  template:
    metadata:
      labels:
        env: dev
        project: My-Happy-Web
        role: frontend
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
